name: Build Childcare Browser

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-app:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: 'Set env values'
      run: |
        pwd
        ls -a
        cd src/wi-childcare-client
        touch .env
        echo VITE_GMAPS_API_KEY=${{secrets.VITE_GMAPS_API_KEY}}
        cat .env
      
   # 
    #- name: Build the Docker image
     # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
